### ISSUE TITLE
Create Entrepreneurial Resources

### ISSUE THREAD

**Issue by agarciaGIT** [SpinOffIntelligence/soiapp#10]
- Allow Research Institutions to relate to other Organizations that supply Entrepreneurial Resources.
- Each Entrepreneurial Resource relation ship can have the following data:

> Name
> Type
> Services
> Area of Assistance
> Specific Need

**Comment by SpinOffIntelligence** [comment]
Hi,

Could you please send me the googgle docs link again? I couldnt open the
link you sent via skype, it says I need a permision.

**Comment by agarciaGIT** [comment]
Done.
