### ISSUE TITLE
Clicking on view details from the network view 

### ISSUE THREAD

**Issue by SpinOffIntelligence** [SpinOffIntelligence/soiapp#8]
Clicking on view details from the network view does not take you back to the organisation profile, like it used to. 

![view details from the network view does not take you back to the organisation profile](https://cloud.githubusercontent.com/assets/23372306/24903115/c20e9fb8-1eac-11e7-8891-8987f68d580d.PNG)

**Comment by SpinOffIntelligence** [comment]
It does seem to be working in most cases. In the image I see the spinner is still going so it may be that it was not done loading (which can be slow once you zoom a lot). I will keep trying to reproduce.

**Comment by agarciaGIT** [comment]
Think this is fixed now.
